# Generated by Django 3.2 on 2021-07-02 09:20

from django.db import migrations, models
import django.db.models.deletion
import reg_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('code', models.CharField(default=reg_profile.models.code_generator, max_length=6)),
                ('subject', models.CharField(choices=[('R', 'registration'), ('P', 'password_reset')], default='R', max_length=1)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration', serialize=False, to='user.user')),
            ],
        ),
    ]
